### ISSUE TITLE
USER STORY: As a Site Admin, I can create, edit, and delete advertisements

### ISSUE THREAD

**Issue by barryCFlynn** [barryCFlynn/WatchBidCentral#1]
As a **Site Admin** I can **create, edit, and delete advertisements** so that ** I can manage the listings on the website effectively.**

## Acceptance Criteria

- Acceptance Criteria 1: I can create a new advertisement with title, description, and set a timer for the expiration.
- Acceptance Criteria 2: I can edit the details of an existing advertisement, including the timer.
- Acceptance Criteria 3: I can delete an advertisement from the website.

## Tasks
- [x] Implement a form for creating new advertisements.
- [x] Implement functionality to edit existing advertisements.
- [x] Implement functionality to delete advertisements.

**Comment by barryCFlynn** [comment]
all acrtions can be carried out with the wbcadmin user account and the Admin panel of the site
